name=NESHardware
version=1.0.0
author=Arduino Port
maintainer=Arduino Port
sentence=Hardware drivers for NES emulator on M5Stack
paragraph=LCD, Audio, and Input drivers for running NES emulator on M5Stack
category=Device Control
url=
architectures=esp32
depends=M5Stack
