#ifndef _SDKCONFIG_H_
#define _SDKCONFIG_H_

#define CONFIG_SOUND_ENA 1

#define CONFIG_HW_PSX_ENA 0
#define CONFIG_HW_PSX_CLK 5
#define CONFIG_HW_PSX_DAT 19
#define CONFIG_HW_PSX_ATT 22
#define CONFIG_HW_PSX_CMD 21

#define CONFIG_HW_LCD_TYPE 1
#define CONFIG_HW_LCD_MISO_GPIO 19
#define CONFIG_HW_LCD_MOSI_GPIO 23
#define CONFIG_HW_LCD_CLK_GPIO 18
#define CONFIG_HW_LCD_CS_GPIO 14
#define CONFIG_HW_LCD_DC_GPIO 27
#define CONFIG_HW_LCD_RESET_GPIO 33
#define CONFIG_HW_LCD_BL_GPIO 32

#define CONFIG_HW_INV_BL 0
#define CONFIG_HW_LCD_CLOCK_SPEED 40000000

#endif
